# Generated by Django 4.2 on 2024-07-30 12:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "behavior",
                    models.CharField(
                        db_comment="действие, которое представляет собой привычка",
                        max_length=200,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        db_comment="дата старта и время, когда необходимо выполнять привычку",
                        verbose_name="Время",
                    ),
                ),
                ("location", models.CharField(max_length=200, verbose_name="Место")),
                (
                    "frequency",
                    models.SmallIntegerField(
                        blank=True,
                        db_comment="периодичность выполнения привычки для напоминания в днях",
                        default=1,
                        null=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        blank=True,
                        db_comment="время, которое предположительно потратит пользователь на выполнение привычки",
                        default=datetime.time(0, 2),
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Признак публичности"
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("is_pleasant_habit", "is_public"),
            },
        ),
    ]
